baseURL: 'https://james.goodhouse.io/'
languageCode: en-us
title: james.goodhouse.io
copyright: © 2021 James Goodhouse
theme: papermod
menu:
  main:
  - identifier: blog
    name: blog
    url: /blog/
    weight: 1
googleAnalytics: G-1F7F1XWKXE
outputs:
  home:
  - HTML
  - RSS
  - JSON # is necessary
params:
  author: James Goodhouse
  description: The home of all things me and the things I love.
  ShowShareButtons: true
  profileMode:
    enabled: true
    title: James Goodhouse
    subtitle: I'm a tech nerd who loves loves trail running, hiking, backpacking, and motorcycling.
    imageUrl: 'headshot.jpg'
    imageTitle: tacobell
    buttons:
    - name: Blog
      url: "/blog"
  socialIcons:
  - name: github
    url: 'https://github.com/jamesgoodhouse/'
  - name: instagram
    url: 'https://www.instagram.com/jamgood96/'
  - name: linkedin
    url: 'https://linkedin.com/in/jamesgoodhouse/'
permalinks:
  blog: /blog/:year/:month/:day/:slug
  tags: /blog/tags/:slug
pluralizelisttitles: false
