baseURL: 'https://james.goodhouse.io/'
languageCode: en-us
title: james.goodhouse.io
copyright: © 2021 James Goodhouse
theme: papermod
menu:
  main:
  - identifier: blog
    name: blog
    url: /blog/
    weight: 1
outputs:
  home:
  - HTML
  - RSS
  - JSON # is necessary
params:
  env: production
  author: James Goodhouse
  ShowShareButtons: true
  profileMode:
    enabled: true
    title: James Goodhouse
    subtitle: I'm a mild tech nerd and an avid outdoor enthusiast that loves running, hiking, backpacking, and motorcycling.
    imageUrl: 'headshot.jpg'
    imageTitle: tacobell
    buttons: []
  socialIcons:
  - name: github
    url: 'https://github.com/jamesgoodhouse/'
  - name: instagram
    url: 'https://www.instagram.com/jamgood96/'
  - name: linkedin
    url: 'https://linkedin.com/in/jamesgoodhouse/'
permalinks:
  blog: /blog/:year/:month/:day/:slug
  tags: /blog/tags/:slug
pluralizelisttitles: false
